name: hackathon-pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOTNET_VERSION: '7.0.x'
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - uses: actions/cache@v3
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore HealthMed.sln

      - name: Build
        run: dotnet build HealthMed.sln --no-restore

  unit-test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - uses: actions/cache@v3
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore HealthMed.sln

      - name: Build
        run: dotnet build HealthMed.sln --no-restore

      - name: UnitTest
        run: dotnet test tests/HealthMed.Application.UnitTests/HealthMed.Application.UnitTests.csproj --no-build --verbosity normal

  architecture-test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - uses: actions/cache@v3
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore HealthMed.sln

      - name: Build
        run: dotnet build HealthMed.sln --no-restore

      - name: ArchitectureTest
        run: dotnet test tests/HealthMed.ArchitectureTests/HealthMed.ArchitectureTests.csproj --no-build --verbosity normal

  container-publish:
    runs-on: ubuntu-latest
    needs: [build, unit-test, architecture-test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login no Container Registry
        uses: docker/login-action@v1.6.0
        with:
          username: ${{ secrets.DOCKER_CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_CONTAINER_REGISTRY_PASSWORD }}

      - name: Build and Push Container Artifact on Docker Hub
        run: |
          docker build . --file src/HealthMed.Api/Dockerfile -t techchallengephase2/healthmed-api:latest
          docker push techchallengephase2/healthmed-api:latest
